name: Deploy Hugo Site

on:
  push:
    branches:
      - main  # Change this to your main branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'

    - name: Build Hugo Site
      run: hugo --minify

    - name: Deploy to Portfolio Repo
      env:
        DEPLOY_KEY: ${{ secrets.HUGO_DEPLOY_KEY }}
      run: |
        # Configure SSH
        mkdir -p ~/.ssh
        echo "${DEPLOY_KEY}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

        # Clone the portfolio repository
        git clone git@github.com:krishna-chandran/portfolio.git deploy_repo

        # Copy generated site to the cloned repository
        rsync -av --delete public/ deploy_repo/

        # Navigate to the deploy_repo directory
        cd deploy_repo

        # Verify the changes
        echo "Files in deploy_repo after rsync:"
        ls -la

        # Commit and push changes
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add .
        git status  # Show the status to confirm changes
        git commit -m "Update site [skip ci]" || echo "No changes to commit"
        git push origin main || echo "Push failed"
        
    - name: Clean Up
      run: |
        # Remove the deploy_repo directory to clean up
        rm -rf deploy_repo
